# Generated by Django 6.0.4 on 2026-04-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.CharField(help_text='One-sentence summary shown on the list page.', max_length=300)),
                ('category', models.CharField(choices=[('chatbot', 'Chatbot'), ('n8n', 'n8n Agent Workflow'), ('langchain', 'LangChain Agent'), ('media', 'Google AI Studio Media'), ('ml', 'Machine Learning (scikit-learn)'), ('django', 'Django'), ('other', 'Other')], default='other', max_length=20)),
                ('business_problem', models.TextField(help_text='The real-world problem this project addresses.')),
                ('tools_used', models.CharField(help_text='Comma-separated, e.g. "Python, Django, OpenAI API".', max_length=300)),
                ('key_features', models.TextField(help_text='One feature per line.')),
                ('role', models.TextField(help_text='Your role and contribution.')),
                ('biggest_challenge', models.TextField()),
                ('lessons_learned', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
