# Generated by Django 6.0.4 on 2026-04-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_biggest_challenge_ja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ja', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.CharField(choices=[('programming_languages', 'Programming Languages'), ('ai_ml', 'AI / Machine Learning'), ('business', 'Business / Sales'), ('languages', 'Languages'), ('tools', 'Tools / Frameworks')], max_length=40)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert'), ('native', 'Native'), ('business_professional', 'Business Professional')], max_length=30)),
                ('icon', models.CharField(blank=True, default='', help_text='Optional emoji or short symbol shown next to the skill name.', max_length=8)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first within a category.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
    ]
